PROBABILITY_POS_ANOMALY = 'probability_pos_anomaly'
PROBABILITY_NEG_ANOMALY = 'probability_neg_anomaly'
POS_ANOMALY_UPPER_RANGE = 'pos_anomaly_upper_range'
POS_ANOMALY_LOWER_RANGE = 'pos_anomaly_lower_range'
NEG_ANOMALY_UPPER_RANGE = 'neg_anomaly_upper_range'
NEG_ANOMALY_LOWER_RANGE = 'neg_anomaly_lower_range'